### ISSUE TITLE
Review Articles for use in Modules

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/p2p-internet-workshop#1]
From the original [planning cryptpad](https://cryptpad.fr/code/#/1/edit/PPnMDKt9FXAeaod3yapSuA/W+OvuS-amhEfcYwVzmWo2Zio/), additional resources in [#reading-networks:tomesh.net](https://chat.tomesh.net/#/room/#reading-networks:tomesh.net):

# Internet Infrastructure & Digital Justice

- Google Fiber, Facebook Internet.org, community meshnets, ISPs, NYC Link, government run municipal broadband and free public WiFi projects. What have we learnt?
- The New Sewer Socialists Are Building an Equitable Internet
https://www.thenation.com/article/the-new-sewer-socialists-are-building-an-equitable-internet/
- Do Artifacts Have Politics
https://transitiontech.ca/pdf/Winner-Do-Artifacts-Have-Politics-1980.pdf
- DC3
https://comconnectivity.org/article/dc3-working-definitions-and-principles/
- Access Rainbow: http://www.web.net/~robrien/papers/access%20rainbow.jpg

# Building a Better Internet

- The Internet We Want @ 27 min (also for general digital justice and algorithmic neutrality)
https://youtu.be/PtO4rPPBWjY?t=27m00s
- Anarchist Perspectives on Net Neutrality
https://crimethinc.com/2017/12/15/anarchist-perspectives-on-net-neutrality-the-digital-enclosure-of-the-commons
- THE WEB BEGAN DYING IN 2014, HERE'S HOW
https://staltz.com/the-web-began-dying-in-2014-heres-how.html
- A PLAN TO RESCUE THE WEB FROM THE INTERNET
https://staltz.com/a-plan-to-rescue-the-web-from-the-internet.html
- Macroscopically Sustainable Networking: On Internet Quines: http://www1.icsi.berkeley.edu/~barath/papers/quine-limits16.pdf

# Mesh Networks of the World - Local Efforts, Internationalist Collaborations

- (Re)BuildingTech
http://communitytechnology.github.io/files/downloads/ReBuildingTech-Zine2.pdf
- DIY networking: the path to a more democratic internet
https://theconversation.com/diy-networking-the-path-to-a-more-democratic-internet-67216

**Comment by benhylau** [comment]
This issue will either live forever or we should incorporate some of these into https://github.com/tomeshnet/p2p-internet-workshop/blob/master/general/extra-resources.md and close. @dcwalk thoughts?

**Comment by dcwalk** [comment]
Would prefer the issue does not live forever. i'm not sure if you even tneed the extra resources (or most of these), I think these got added form reading networks and most aren't appropriate for a workshop format?

I just did a copy-paste from the planning pad.

**Comment by dcwalk** [comment]
I'M GONNA CLOSE THIS> If we discover something missing let's add in? Just didn't want it too disappear too early, but now feels like time 👋 🌊
