### ISSUE TITLE
Add Facilitation Guidelines for Session leaders

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/p2p-internet-workshop#27]
We talked about a couple techniques we will adopt for the workshop, these guidelines/notes need to be added:

- Signalling volunteers for hands-on sections
- "Pair teaching" (with someone observing and providing feedback after
- Shared notepad
- "Ticket out the door"
- Jargon-busting

**Comment by benhylau** [comment]
Should be addressed in https://github.com/tomeshnet/p2p-internet-workshop/pull/25 README.md
