### ISSUE TITLE
Draft intro email (include shell and installation resources)

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/p2p-internet-workshop#29]
This has preliminarily been completed in #28, things it needs:

- [x] email language (with install, shell instructions)
- [x] survey md template
- [x] link to intro commands?
- [x] (and) set up actual survey
   - [x] Pre-workshop survey: https://www.surveymonkey.com/r/2GJ2XZR
   - Post-workshop survey (handled in different issue)

**Comment by dcwalk** [comment]
this is ready pretty much to be sent off

**Comment by benhylau** [comment]
Sent out yesterday. Thanks @dcwalk and @darkdrgn2k 👍
