### ISSUE TITLE
Add template for shared notepad to repo

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/p2p-internet-workshop#30]
Stable pad address is: https://pad.riseup.net/p/peer-to-peer-internet

This should cover the following (per 2018-04-05 runthrough):

- intro shell commands: (https://swcarpentry.github.io/shell-novice/02-filedir/; https://swcarpentry.github.io/shell-novice/01-intro/)
  - $
  - `pwd`
  - `ls`
  - `cd`
  - `..`, `.`, `~`,
  - something on <programs> <paths>? `-` or `--` flags, `/`
- jargon terms
  - host
  - hash
  - node
  - ssh
  - session
  - IPFS
  - SSID
  - interface
  - raspberry pi
  - access point
  - point-to-point
  - p2p
  - protocol
  - hostname
  - commandline/shell/cli/terminal
  - ping
  - docker
  - gateway
  - cjdns
  - daemon

**Comment by benhylau** [comment]
Also, this exists: https://github.com/tomeshnet/tomesh.101/blob/master/glossary/glossary.md

**Comment by Shrinks99** [comment]
Shared notepads / glossaries should be revisited as part of the content overhaul, perhaps on the next workshop call.

**Comment by benhylau** [comment]
I feel this hasn't been useful, especially the shared pad. Should rethink how this is presented. Maybe as a printout?

**Comment by Shrinks99** [comment]
I like the printout idea, perhaps included with the proposed SSH worksheet?

**Comment by Shrinks99** [comment]
This module is being closed in favour of moving most of the jargon busting into the [SSH worksheet](#74) as decided upon in today's workshop call
