### ISSUE TITLE
Course website

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/p2p-internet-workshop#33]
Let's make a proper course website on GitHub Pages. We are currently hosting generated assets and presentations:

https://github.com/tomeshnet/p2p-internet-workshop/tree/gh-pages
https://tomeshnet.github.io/p2p-internet-workshop/module-1-presentation/

But we can have a proper static website at https://tomeshnet.github.io/p2p-internet-workshop/ that describes the course and links to all the materials.

**Comment by Shrinks99** [comment]
Course website is being covered in more detail with other issues and the [Workshop Website milestone](https://github.com/tomeshnet/p2p-internet-workshop/milestone/2).
