### ISSUE TITLE
Design and mockup for course website

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/p2p-internet-workshop#38]
Resources are spread across many repositories. In the current state it is very difficult for someone unfamiliar to gather everything to facilitate even a single module of the workshop.

**Hardware:**

* Raspberry Pi 3s
* or Raspberry Pi 2s (with extra USB adapter)
* USB WiFi adapters supporting mesh point and ad-hoc
* SD cards
* Materials for LoRa (Module 6 cc. @uditvira)

**Software:**

* https://github.com/tomeshnet/mesh-orange
* https://github.com/benhylau/mesh-router-builder (with [specific config](https://github.com/benhylau/mesh-router-builder/tree/master/src/mesh-orange-images/mesh-orange))
* https://github.com/benhylau/mesh-workshop (with [specific branches](https://github.com/benhylau/mesh-workshop/pulls))

**Workshop Materials:**

* Released to [GitHub Releases and GitHub Pages](https://github.com/tomeshnet/p2p-internet-workshop#workshop-materials)

**Facilitation Guidelines:**

* There are a bunch of optional tools, some of them not being used

**External Assets:**

* Hosted content on YouTube and other sites, especially for Homework, require internet to access, we should indicate which pieces need internet

We need to design how to present this in a way that others can easily gather everything and facilitate in a no Internet setting.

**Comment by patcon** [comment]
Could steal some scaffold from this: https://mozilla.github.io/open-leadership-training-series/

**Comment by dcwalk** [comment]
Might want to use hugo for building to have `RelativePaths` option (better handling of hosting on ipfs)? (is that an eventual goal? Thought that was mentioned in a conversation at some point)

**Comment by benhylau** [comment]
@patcon you have no idea how much time you saved me -> https://tomeshnet.github.io/p2p-internet-workshop/

**Comment by benhylau** [comment]
@dcwalk I am not familiar with hugo and have no context as to what `RelativePath` means in the context of hugo and ipfs. I'd think our site, since it is static, will host on ipfs just fine regardless of build tool, no?

Our travis file is super simple because complex logic are all done in the three scripts. The important thing for a CI tool is that it has GitHub Releases and Pages integrations as travis does. If hugo supports the same it should not be difficult to port in the future.

**Comment by dcwalk** [comment]
There is an issue with how paths are written using jekyll that make it a headache, lots of broken links to troubleshoot when serving (see [here](https://discuss.ipfs.io/t/any-one-publishing-a-jekyll-blog-on-ipfs/651/5)). Though it looks like there are some recent [attempts (1)](https://discuss.ipfs.io/t/publishing-a-jekyll-blog-on-ipfs/3139) [(2)](https://gist.github.com/claus/1287f47b5fbaaea338ac8a04d02bf258) to deal with those

**Comment by benhylau** [comment]
Ahh you mean the website build, I thought you were referring to the CI system. I clearly have no idea what hugo is. Since we now have the website done using Jekyll and I see no immediate need for it to go onto ipfs, and the Jekyll support is evolving, I suggest we leave as is and keep hugo in mind for future?

**Comment by dcwalk** [comment]
yeah no rush. I just remember conversations about wanting to host on ipfs/on nodes (maybe I'm merging discussions?) and wanted to surface that consideration

**Comment by Shrinks99** [comment]
Can this be closed?

**Comment by benhylau** [comment]
I added this https://github.com/tomeshnet/p2p-internet-workshop/pull/84 to complete the Software/Hardware setup instructions, so now the site does contain everything. _Facilitation Guidelines_ and _External Assets_ can probably be better presented, but they are on the site now.

I am closing this since some of the presentation and site re-theming work already has their own tickets. Feel free to re-open if anyone has objections.
