### ISSUE TITLE
Package course material for distribution

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/p2p-internet-workshop#41]
Course material should be packaged into a .zip and .tgz for distribution to presenters.

### Each Module Contains:

- A presentation to give and the associated files
- A `handouts` folder containing printed documents to give to the class
- Presenter instructions

All applicable written / visual material should be presented as a Remark HTML presentation. 
 Presenters should not be required to interface with anything used to build those resources!

Software resources should be packaged into separate .zip and .tgz files.

**Comment by benhylau** [comment]
This looks fine for the packages, but we also spoke about hosted materials that are for instructors to check out, use in class if they wish, and students to review. I think those are key pieces we need to address as well, as well as items on [this ticket we looked through](https://github.com/tomeshnet/p2p-internet-workshop/issues/38) such as `External Assets`.

**Comment by Shrinks99** [comment]
External assets are absolutely important to work though, ideally we can include as many as possible with the course for offline use.  Online hosted material (most likely a GitBook as a part of the website) is a website feature.

**Comment by Shrinks99** [comment]
Closing this issue as part of the Remark overhaul (and arguably before that even) everything here has been dealt with as part of the build script.
