### ISSUE TITLE
Investigate self-guided version

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/p2p-internet-workshop#50]
Self-guided format examples:

* [nodeschool.io](https://nodeschool.io)
* [Rust by Example](https://doc.rust-lang.org/rust-by-example/)
* [Kotlin Koans](https://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Hello,%20world!/Task.kt) which can be run offline with IDE integration
* [proto.school](http://proto.school) probably can be made to run in an off-Internet IPFS network

[Mesh Workshop](https://github.com/benhylau/mesh-workshop) is a primitive version covering some of the concepts in this course, requiring specific hardware, as in this course.

**Comment by Shrinks99** [comment]
As we move to a modularized system of presenter resources is this still something to consider?  This concept could possibly be better served as a separate project where content is not dependant on a presenter —> student relationship.  Admittedly i don't have time to construct such a thing....

I think I'd personally rather stick with tailoring content to this environment, that's not to say the content instructional couldn't be duplicated to a self-driven scenario later on but I don't think it should be a focus for the workshop.

**Comment by benhylau** [comment]
Probably a good discussion item for our meeting, what are the settings we want to design for?

We have so far talked about:

- _2-hour technical workshop with facilitator and helpers_
  - e.g. Toronto Mesh workshop Raspberry Pi hands-on
- _1-hour social activity_
  - e.g. drawing activity
  - e.g. Toronto Mesh workshop social activities
- _15-minute skill station_
  - e.g. People's Open's stations

I wonder if [materials like this](https://benhylau.github.io/talks-and-workshops/talks/201810_radical-networks-lightning/#1) can even be made into a format like:

- _15-min lightning talk_

Or in this ticket:

- _1-hour self-guided_

I think it's good (at least to begin with) that we limit to a small set of formats. Thinking about **time required + presentation environment** as categories is probably a good place to start our new initiative.

**Comment by benhylau** [comment]
De-scoping from this project by consensus at 26 March 2019 meeting of working group @futurefarmer @Shrinks99 @bennlich @benhylau. Favour focusing on facilitated activities.

**Comment by amberinitiative** [comment]
De-scoping this from the Mesh Workshop is good. But I do think follow-up material and self-study videos are helpful. I also like this format, mixed with some interactivity and videos:

-http://devopsbootcamp.osuosl.org/start-here.html
