### ISSUE TITLE
Mesh Point Interface ....... [INACTIVE]

### ISSUE THREAD

**Issue by santhoshnp** [tomeshnet/p2p-internet-workshop#61]
![screenshot 71](https://user-images.githubusercontent.com/39831264/45801306-2b926000-bcd1-11e8-9406-c747eccd21f3.png)

**Comment by santhoshnp** [comment]
How to activate mesh interfaces

**Comment by benhylau** [comment]
I responded to you in the prototype repo. Please stop filing the same issue in every tomesh repo.
