### ISSUE TITLE
Convert all workshop slides over to Remark presentations

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/p2p-internet-workshop#75]
Conversion tracking of presentation slides from GitBook to the Remark format as outlined in #44.  Ideally we freeze all content for modules that are checked off here on the main branch?  It doesn't _have_ to be done but would make my life easier.  Work will be started with Module 1 and once the build process is fully finished everything else will be handled.

- [x] Module 1
- [x] Module 2
- [x] Module 3
- [x] Module 4
- [x] Module 5
- [x] Module 6

**Comment by Shrinks99** [comment]
Module 1 has been partially implemented in the [remark-module-1](https://github.com/tomeshnet/p2p-internet-workshop/tree/remark-module-1) branch.  It is not currently integrated into the build script and guidance is needed from @benhylau about web server usage for the PDF generation.

Decktape has been added to the dependency install script

**Comment by benhylau** [comment]
Move the files into the correct directory structure first then we can deal with the build scripts, see: https://github.com/tomeshnet/p2p-internet-workshop/issues/81#issuecomment-449265952
