### ISSUE TITLE
Host Fonts Locally

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/p2p-internet-workshop#83]
Fonts are not hosted locally for the markdown to PDF conversion or Remark.  This should really be done to allow everything to be built without internet access.

**Comment by benhylau** [comment]
@Shrinks99 it's not a bug if it's a missing feature in a branch that hasn't been merged. The current version works just fine without Internet access. And as I have pointed out "markdown to PDF conversion" can have build-time Internet dependencies, just not the local presentation website.

**Comment by benhylau** [comment]
This would better belong as a subtask in the "gitbook -> remark" conversion itself. I suggest to move and close so it doesn't confuse users of current release.

**Comment by Shrinks99** [comment]
Alrighty
